//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Domain.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        [Key]
        public int ReviewId { get; set; }
        public string ClientName { get; set; }
        public string ClientFeedback { get; set; }
        public Nullable<int> Rating { get; set; }
        public System.DateTime DateFeedback { get; set; }
    }
}
