//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entityes
{
    using System;
    
    public partial class Reviews
    {
        public int ReviewId { get; set; }
        public string ClientName { get; set; }
        public string ClientFeedback { get; set; }
        public int? Rating { get; set; }
        public DateTime DateFeedback { get; set; }
    }
}
