//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public string StatusName { get; set; }
        public int StatusId { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
